version: '3'
services:
  node:
    image: node:17-alpine3.12
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html:cached
    ports:
      - "3000:3000"
    environment:
      - GFYCAT_CLIENT_ID=
      - GFYCAT_SECRET=
    command: sh -c "npm run dev"

